### ISSUE TITLE
Inmediate delete on backspace

### ISSUE THREAD

**Issue by cospin** [Ralfarios/antd-input-otp#13]
Hello, thank you for this package, it's really helpful.

When pressing the backspace button, in the current behavior, it only focuses and selects the number in the previous input, you have to press it again to delete the number. I believe it should immediately delete the input, as it works on most sites. If you are in an empty input and press backspace, the previous input gets cleared and gets focused.

Thanks!

**Comment by Ralfarios** [comment]
Hello, and thank you for using antd-input-otp.. I will work on this ASAP on the next update 1.1.1.. 

Cheers, 
R.

**Comment by Ralfarios** [comment]
Hello, @cospin ,

Thanks for waiting. In the current version (1.1.1), the `Backspace` key behaviour is also has been fixed along side the `Enter` key behaviour. Hope you can use it smoothly on your project.

Cheers,
R.

**Comment by kolnogorov** [comment]
Thank you for a great library!
But this bug is still present in 2.1.0.

**Comment by Ralfarios** [comment]
> Thank you for a great library! But this bug is still present in 2.1.0.

Hello, thank you.

May I know which browser are you using?
